#A user get their own bookorder lists
query{
  listBookings{
    items{
      id
      dateFrom
      dateTo
      total
      rooms{
        items{
          room{
            id
        name
        type
        description
        price
        capacity
        pets
        image
        featured
        breakfast
          }
        }
      }
    }
  }
}